# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Release1

pool:
  vmImage: ubuntu-latest


stages:  
  - stage: BuildDev
    displayName: build for Dev
    jobs:   
      - job: BuildMobileApp   
        displayName: Mobiles for Dev   
        steps:
          - script: echo build mobile aplication
            displayName: Build mobile app 
          - script:  echo running united test
            displayName: Build mobile app 
      - job: BuildReactApp  
        displayName: React for Dev      
        steps:
          - script: echo build React aplication
            displayName: Build React app 
          - script:  echo running united test
            displayName: Build React app 
      - job: BuildNodeApp
        displayName: NodeJs for Dev
        steps:
          - script: echo build React aplication
            displayName: Build React app 
          - script:  echo running united test
            displayName: Build React app 