# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Release1

pool:
  vmImage: ubuntu-latest


stages:  
  - stage: BuildDev
    displayName: build for Dev
    jobs:   
      - job: BuildMobileApp   
        displayName: Mobiles for Dev   
      - job: BuildReactApp  
        displayName: React for Dev      
      - job: BuildNodeApp
        displayName: NodeJs for Dev   
  - stage: BuildQA
    displayName: build for Staging
    jobs:   
      - job: BuildMobileApp   
        displayName: Mobiles for Staging      
      - job: BuildReactApp  
        displayName: React for Staging   
      - job: BuildNodeApp
        displayName: NodeJs for Staging
  - stage: BuildProd
    displayName: build for Prod
    jobs:   
      - job: BuildMobileApp   
        displayName: Mobiles for Prod
      - job: BuildReactApp  
        displayName: React for Prod   
      - job: BuildNodeApp
        displayName: NodeJs for Prod
       